// components/analysis/LLMDisclaimerBanner.jsx

import React from 'react';
import { ShieldAlert, Info } from 'lucide-react';

export default function LLMDisclaimerBanner({ warnings }) {
  if (!warnings || !warnings.length) {
    return null;
  }

  return (
    <div className="bg-red-50 border-l-4 border-red-500 text-red-700 p-4 rounded-lg shadow-md mb-6">
      <div className="flex items-start">
        <ShieldAlert className="w-6 h-6 mr-3 mt-1 flex-shrink-0 text-red-600" />
        <div>
          <h3 className="text-lg font-bold mb-1">
            ⚠️ LLM Risk & Legal Disclaimer Required
          </h3>
          <p className="text-sm font-semibold mb-2">
            This analysis was generated by a Large Language Model (LLM).
          </p>
          <ul className="list-disc ml-6 space-y-1 text-sm">
            {warnings.map((warning, index) => (
              <li key={index} className="flex items-start">
                <Info className="w-4 h-4 mt-0.5 mr-2 text-red-500 flex-shrink-0" />
                <span className='font-medium'>{warning}</span>
              </li>
            ))}
          </ul>
          <p className="mt-3 text-xs italic">
            **FINAL RESPONSIBILITY FOR CONTRACT INTERPRETATION RESTS WITH THE USER.**
          </p>
        </div>
      </div>
    </div>
  );
}